services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ./uploads:/server/uploads

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5433:5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://challenge.mlk-labs.com/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db_postgres:
  grafana_data:
  es_data: