version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ./uploads:/server/uploads

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://challenge.mlk-labs.com/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana


  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.6.1
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yaml


volumes:
  db_postgres:
  grafana_data: